### PR TITLE
init spec for non revocation token

### PR DESCRIPTION
**Pull request by brianorwhatever**
I have copied your hackmd file into a basic spec-up

### CODE REVIEW

**Comment by andrewwhitehead** [comment]
It looks like KaTeX support in spec-up is commented out? :(

https://github.com/decentralized-identity/spec-up/blob/598eec7fc6920b866b4e07c237943bf82a3c9d23/index.js#L120

**Comment by brianorwhatever** [comment]
hmm yeah I see it really messes up the spec. Wonder why it's disabled. Maybe it never worked I'm not sure I've seen any DIF specs with fancy math in them..

**Comment by andrewwhitehead** [comment]
Added a PR for that: https://github.com/decentralized-identity/spec-up/pull/42

**Comment by brianorwhatever** [comment]
added workaround. need to copy katex enabled spec-up into node modules. will remove once other PR ever gets merged. Merging this spec init in

**Pull request merged**
